var cy = window.cy = cytoscape({
  container: document.getElementById('cy'),

  boxSelectionEnabled: false,
  autounselectify: true,

  layout: {
    name: 'dagre',
    nodeSep: 20,
    edgeSep: 0,
    rankDir: 'LR',
    rankSep: 20,
    align: 'UR',
  },


  style: [
    {
      selector: 'node',
      style: {
        'content': 'data(id)',
        'text-opacity': 0.5,
        'text-valign': 'center',
        'text-halign': 'right',
        'background-color': '#11479e'
      }
    },

    {
      selector: 'edge',
      style: {
        'width': 4,
        'target-arrow-shape': 'triangle',
        'line-color': '#9dbaea',
        'target-arrow-color': '#9dbaea'
      }
    }

  ],

  elements: {
    nodes: [
      { data: { id: 'n1' } },
      { data: { id: 'n2' } },
      { data: { id: 'n3' } },
      { data: { id: 'n4' } },
      { data: { id: 'n5' } },
      { data: { id: 'n6' } },
      { data: { id: 'n7' } },
      { data: { id: 'n8' } },
      { data: { id: 'n9' } },
      { data: { id: 'n10' } },
      { data: { id: 'n11' } },
      { data: { id: 'n12' } },
      { data: { id: 'n13' } },
      { data: { id: 'n14' } },
      { data: { id: 'n15' } },
      { data: { id: 'n16' } },
      { data: { id: 'n18' } },
      { data: { id: 'n19' } },
      { data: { id: 'n20' } },
      { data: { id: 'n21' } },
      { data: { id: 'n22' } },
      { data: { id: 'n23' } },
      { data: { id: 'n24' } },
      { data: { id: 'n1_s' } },
      { data: { id: 'n14_s' } },
      { data: { id: 'n15_s' } },
      { data: { id: 'n22_s' } },
      { data: { id: 'n23_s' } },
      { data: { id: 'n4_s' } },
      { data: { id: 'n5_s' } },
      { data: { id: 'n6_s' } },
    ],
    edges: [
      { data: { source: 'n3', target: 'n19' } },
      { data: { source: 'n3', target: 'n21' } },
      { data: { source: 'n5_s', target: 'n20' } },
      { data: { source: 'n5_s', target: 'n11' } },
      { data: { source: 'n9', target: 'n6' } },
      { data: { source: 'n10', target: 'n4' } },
      { data: { source: 'n11', target: 'n5' } },
      { data: { source: 'n12', target: 'n22' } },
      { data: { source: 'n15_s', target: 'n16' } },
      { data: { source: 'n15_s', target: 'n18' } },
      { data: { source: 'n16', target: 'n13' } },
      { data: { source: 'n20', target: 'n8' } },
      { data: { source: 'n20', target: 'n9' } },
      { data: { source: 'n22_s', target: 'n12' } },
      { data: { source: 'n22_s', target: 'n2' } },
      { data: { source: 'n1_s', target: 'n19' } },
      { data: { source: 'n1_s', target: 'n21' } },
      { data: { source: 'n2', target: 'n7' } },
      { data: { source: 'n2', target: 'n24' } },
      { data: { source: 'n4_s', target: 'n3' } },
      { data: { source: 'n4_s', target: 'n10' } },
      { data: { source: 'n6_s', target: 'n8' } },
      { data: { source: 'n6_s', target: 'n9' } },
      { data: { source: 'n7', target: 'n14' } },
      { data: { source: 'n8', target: 'n3' } },
      { data: { source: 'n8', target: 'n10' } },
      { data: { source: 'n13', target: 'n23' } },
      { data: { source: 'n14_s', target: 'n7' } },
      { data: { source: 'n14_s', target: 'n24' } },
      { data: { source: 'n18', target: 'n15' } },
      { data: { source: 'n19', target: 'n12' } },
      { data: { source: 'n19', target: 'n2' } },
      { data: { source: 'n21', target: 'n1' } },
      { data: { source: 'n23_s', target: 'n13' } },
      { data: { source: 'n24', target: 'n16' } },
      { data: { source: 'n24', target: 'n18' } },
    ]
  }

  // elements: {
  //   nodes: [
  //     { data: { id: 'A0' } },
  //     { data: { id: 'A1' } },
  //     { data: { id: 'A2' } },
  //     { data: { id: 'A4' } },
  //     { data: { id: 'A5' } },
  //     { data: { id: 'A6' } },
  //     { data: { id: 'B0' } },
  //     { data: { id: 'B1' } },
  //     { data: { id: 'B2' } },
  //     { data: { id: 'B3' } },
  //     { data: { id: 'B4' } },
  //     { data: { id: 'B5' } },
  //     { data: { id: 'B6' } },
  //     { data: { id: 'C0' } },
  //     { data: { id: 'C1' } },
  //     { data: { id: 'C2' } },
  //     { data: { id: 'C3' } },
  //     { data: { id: 'C4' } },
  //     { data: { id: 'C5' } },
  //     { data: { id: 'C6' } },
  //   ],
  //   edges: [
  //     { data: { source: 'A6', target: 'B6' } },
  //     { data: { source: 'A5', target: 'B6' } },
  //     { data: { source: 'A0', target: 'B1' } },
  //     { data: { source: 'A4', target: 'B1' } },
  //     { data: { source: 'A1', target: 'B0' } },
  //     { data: { source: 'A0', target: 'B0' } },
  //     { data: { source: 'A6', target: 'B5' } },
  //     { data: { source: 'A4', target: 'B5' } },
  //     { data: { source: 'A1', target: 'B2' } },
  //     { data: { source: 'A2', target: 'B2' } },
  //     { data: { source: 'A2', target: 'B3' } },
  //     { data: { source: 'A1', target: 'B3' } },
  //     { data: { source: 'A4', target: 'B4' } },
  //     { data: { source: 'A5', target: 'B4' } },
  //     { data: { source: 'B2', target: 'C1' } },
  //     { data: { source: 'B1', target: 'C1' } },
  //     { data: { source: 'B4', target: 'C4' } },
  //     { data: { source: 'B3', target: 'C4' } },
  //     { data: { source: 'B3', target: 'C3' } },
  //     { data: { source: 'B4', target: 'C3' } },
  //     { data: { source: 'B0', target: 'C0' } },
  //     { data: { source: 'B2', target: 'C0' } },
  //     { data: { source: 'B4', target: 'C2' } },
  //     { data: { source: 'B2', target: 'C2' } },
  //     { data: { source: 'B5', target: 'C6' } },
  //     { data: { source: 'B6', target: 'C6' } },
  //     { data: { source: 'B5', target: 'C5' } },
  //     { data: { source: 'B4', target: 'C5' } },
  //   ]
  // }

  // elements: {
  //   nodes: [
  //     { data: { id: 'n0' } },
  //     { data: { id: 'n1' } },
  //     { data: { id: 'n2' } },
  //     { data: { id: 'n3' } },
  //     { data: { id: 'n4' } },
  //     { data: { id: 'n5' } },
  //     { data: { id: 'n6' } },
  //     { data: { id: 'n7' } },
  //     { data: { id: 'n8' } },
  //     { data: { id: 'n9' } },
  //     { data: { id: 'n10' } },
  //     { data: { id: 'n11' } },
  //     { data: { id: 'n12' } },
  //     { data: { id: 'n13' } },
  //     { data: { id: 'n14' } },
  //     { data: { id: 'n15' } },
  //     { data: { id: 'n16' } }
  //   ],
  //   edges: [
  //     { data: { source: 'n0', target: 'n1' } },
  //     { data: { source: 'n1', target: 'n2' } },
  //     { data: { source: 'n1', target: 'n3' } },
  //     { data: { source: 'n4', target: 'n5' } },
  //     { data: { source: 'n4', target: 'n6' } },
  //     { data: { source: 'n6', target: 'n7' } },
  //     { data: { source: 'n6', target: 'n8' } },
  //     { data: { source: 'n8', target: 'n9' } },
  //     { data: { source: 'n8', target: 'n10' } },
  //     { data: { source: 'n11', target: 'n12' } },
  //     { data: { source: 'n12', target: 'n13' } },
  //     { data: { source: 'n13', target: 'n14' } },
  //     { data: { source: 'n13', target: 'n15' } },
  //   ]
  // },

});

console.log(cy);
